<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if books already exist
        if (Book::count() > 0) {
            $this->command->info('Books already seeded. Skipping...');
            return;
        }

        $books = [
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'isbn' => '9780262033848',
                'description' => 'Comprehensive introduction to algorithms',
                'publisher' => 'MIT Press',
                'publication_year' => 2009,
                'quantity' => 15,
                'available_quantity' => 15,
                'shelf_location' => 'A1-S3',
                'category' => 'Computer Science',
                //  'semester' => 3,
                'is_available' => true,
                'course_id' => 1,
            ],
            [
                'title' => 'Digital Electronics',
                'author' => 'William Stallings',
                'isbn' => '9781259025471',
                'description' => 'Fundamentals of digital electronics and circuit design',
                'publisher' => 'Pearson',
                'publication_year' => 2017,
                'quantity' => 12,
                'available_quantity' => 12,
                'shelf_location' => 'B2-S1',
                'category' => 'Electronics',
                //  'semester' => 2,
                'course_id' => 2,
                'is_available' => true,
            ],
            [
                'title' => 'Thermodynamics: An Engineering Approach',
                'author' => 'Yunus A. Cengel',
                'isbn' => '9780073398174',
                'description' => 'Comprehensive study of thermodynamics for engineers',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2014,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'C3-S2',
                'category' => 'Mechanical Engineering',
                //  'semester' => 4,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Principles of Management',
                'author' => 'Peter F. Drucker',
                'isbn' => '9780062836489',
                'description' => 'Essential guide to business management principles',
                'publisher' => 'Harper Business',
                'publication_year' => 2019,
                'quantity' => 20,
                'available_quantity' => 20,
                'shelf_location' => 'D1-S4',
                'category' => 'Business',
                //  'semester' => 1,
                'course_id' => 7,
                'is_available' => true,
            ],
            [
                'title' => 'Advanced Calculus',
                'author' => 'James Stewart',
                'isbn' => '9781285741550',
                'description' => 'In-depth exploration of calculus concepts',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2015,
                'quantity' => 8,
                'available_quantity' => 8,
                'shelf_location' => 'E2-S3',
                'category' => 'Mathematics',
                //  'semester' => 2,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Data Structures and Algorithms',
                'author' => 'Robert Sedgewick',
                'isbn' => '9780321573513',
                'description' => 'Comprehensive guide to data structures and algorithms',
                'publisher' => 'Addison-Wesley',
                'publication_year' => 2011,
                'quantity' => 18,
                'available_quantity' => 18,
                'shelf_location' => 'A2-S2',
                'category' => 'Computer Science',
                //  'semester' => 4,
                'course_id' => 1,
                'is_available' => true,
            ],
            [
                'title' => 'Microelectronic Circuits',
                'author' => 'Adel S. Sedra',
                'isbn' => '9780199339136',
                'description' => 'Analysis and design of electronic circuits',
                'publisher' => 'Oxford University Press',
                'publication_year' => 2020,
                'quantity' => 14,
                'available_quantity' => 14,
                'shelf_location' => 'B3-S4',
                'category' => 'Electronics',
                //  'semester' => 3,
                'course_id' => 4,
                'is_available' => true,
            ],
            [
                'title' => 'Introduction to Computer Science',
                'author' => 'John Doe',
                'isbn' => '9781234567890',
                'description' => 'A comprehensive guide to CS basics',
                'publisher' => 'Academic Press',
                'publication_year' => 2023,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'A-12',
                'category' => 'Computer Science',
                //  'semester' => 1,
                'course_id' => 10,
                'is_available' => true,
            ],
            [
                'title' => 'Operating System Concepts',
                'author' => 'Abraham Silberschatz',
                'isbn' => '9781119456339',
                'description' => 'Fundamentals of operating system design and implementation',
                'publisher' => 'Wiley',
                'publication_year' => 2018,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'A4-S1',
                'category' => 'Computer Science',
                //  'semester' => 5,
                'course_id' => 1,
                'is_available' => true,
            ],
            [
                'title' => 'Signals and Systems',
                'author' => 'Alan V. Oppenheim',
                'isbn' => '9780138147570',
                'description' => 'Comprehensive analysis of signals and systems',
                'publisher' => 'Pearson',
                'publication_year' => 2016,
                'quantity' => 12,
                'available_quantity' => 12,
                'shelf_location' => 'B1-S2',
                'category' => 'Electronics',
                //  'semester' => 4,
                'course_id' => 2,
                'is_available' => true,
            ],
            [
                'title' => 'Fluid Mechanics',
                'author' => 'Frank M. White',
                'isbn' => '9780073398273',
                'description' => 'Principles and applications of fluid mechanics',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2017,
                'quantity' => 9,
                'available_quantity' => 9,
                'shelf_location' => 'C2-S4',
                'category' => 'Mechanical Engineering',
                //  'semester' => 3,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Marketing Management',
                'author' => 'Philip Kotler',
                'isbn' => '9780133856460',
                'description' => 'Comprehensive guide to marketing principles',
                'publisher' => 'Pearson',
                'publication_year' => 2015,
                'quantity' => 13,
                'available_quantity' => 13,
                'shelf_location' => 'D3-S1',
                'category' => 'Business',
                //  'semester' => 2,
                'course_id' => 8,
                'is_available' => true,
            ],
            [
                'title' => 'Linear Algebra and Its Applications',
                'author' => 'Gilbert Strang',
                'isbn' => '9780030105678',
                'description' => 'Foundational concepts in linear algebra',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2016,
                'quantity' => 7,
                'available_quantity' => 7,
                'shelf_location' => 'E1-S2',
                'category' => 'Mathematics',
                //  'semester' => 3,
                'course_id' => 11,
                'is_available' => true,
            ],
            [
                'title' => 'Computer Networking: A Top-Down Approach',
                'author' => 'James F. Kurose',
                'isbn' => '9780133594140',
                'description' => 'Layered approach to understanding networking systems',
                'publisher' => 'Pearson',
                'publication_year' => 2021,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'A5-S1',
                'category' => 'Computer Science',
                //  'semester' => 5,
                'course_id' => 4,
                'is_available' => true,
            ],
            [
                'title' => 'Analog Electronics',
                'author' => 'Jacob Millman',
                'isbn' => '9780070704565',
                'description' => 'Design and analysis of analog electronic circuits',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2014,
                'quantity' => 11,
                'available_quantity' => 11,
                'shelf_location' => 'B2-S3',
                'category' => 'Electronics',
                //  'semester' => 2,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Strength of Materials',
                'author' => 'R. K. Bansal',
                'isbn' => '9788174091950',
                'description' => 'Fundamentals of materials under stress and strain',
                'publisher' => 'Laxmi Publications',
                'publication_year' => 2012,
                'quantity' => 8,
                'available_quantity' => 8,
                'shelf_location' => 'C4-S1',
                'category' => 'Mechanical Engineering',
                //  'semester' => 2,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Financial Accounting',
                'author' => 'T.S. Grewal',
                'isbn' => '9788183505824',
                'description' => 'Introduction to accounting principles and procedures',
                'publisher' => 'S. Chand',
                'publication_year' => 2019,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'D2-S2',
                'category' => 'Business',
                //  'semester' => 1,
                'course_id' => 9,
                'is_available' => true,
            ],
            [
                'title' => 'Probability and Statistics',
                'author' => 'Miller and Freund',
                'isbn' => '9788131719933',
                'description' => 'Essential guide to probability and statistical methods',
                'publisher' => 'Pearson',
                'publication_year' => 2013,
                'quantity' => 12,
                'available_quantity' => 12,
                'shelf_location' => 'E4-S2',
                'category' => 'Mathematics',
                //  'semester' => 4,
                'course_id' => 8,
                'is_available' => true,
            ],
            [
                'title' => 'Database System Concepts',
                'author' => 'Henry F. Korth',
                'isbn' => '9780078022159',
                'description' => 'Fundamental concepts in database systems',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2019,
                'quantity' => 14,
                'available_quantity' => 14,
                'shelf_location' => 'A6-S1',
                'category' => 'Computer Science',
                //  'semester' => 5,
                'course_id' => 12,
                'is_available' => true,
            ],
            [
                'title' => 'Embedded Systems',
                'author' => 'Raj Kamal',
                'isbn' => '9780070151253',
                'description' => 'Design and programming of embedded systems',
                'publisher' => 'McGraw-Hill',
                'publication_year' => 2011,
                'quantity' => 9,
                'available_quantity' => 9,
                'shelf_location' => 'B4-S1',
                'category' => 'Electronics',
                //  'semester' => 5,
                'course_id' => 13,
                'is_available' => true,
            ],
            [
                'title' => 'Machine Design',
                'author' => 'V. B. Bhandari',
                'isbn' => '9780070681799',
                'description' => 'Design of mechanical components and systems',
                'publisher' => 'Tata McGraw-Hill',
                'publication_year' => 2016,
                'quantity' => 7,
                'available_quantity' => 7,
                'shelf_location' => 'C5-S3',
                'category' => 'Mechanical Engineering',
                //  'semester' => 5,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Business Communication',
                'author' => 'Meenakshi Raman',
                'isbn' => '9780199457069',
                'description' => 'Effective communication in business settings',
                'publisher' => 'Oxford University Press',
                'publication_year' => 2015,
                'quantity' => 15,
                'available_quantity' => 15,
                'shelf_location' => 'D4-S4',
                'category' => 'Business',
                //  'semester' => 2,
                'course_id' => 7,
                'is_available' => true,
            ],
            [
                'title' => 'Discrete Mathematics',
                'author' => 'Kenneth H. Rosen',
                'isbn' => '9780073383096',
                'description' => 'Mathematical structures in computer science',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2012,
                'quantity' => 11,
                'available_quantity' => 11,
                'shelf_location' => 'E3-S1',
                'category' => 'Mathematics',
                //  'semester' => 2,
                'course_id' => 12,
                'is_available' => true,
            ],
            [
                'title' => 'Computer Organization and Design',
                'author' => 'David A. Patterson',
                'isbn' => '9780128122754',
                'description' => 'Hardware and software interface of computer systems',
                'publisher' => 'Morgan Kaufmann',
                'publication_year' => 2017,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'A7-S1',
                'category' => 'Computer Science',
                //  'semester' => 4,
                'course_id' => 12,
                'is_available' => true,
            ],
            [
                'title' => 'Control Systems Engineering',
                'author' => 'Norman S. Nise',
                'isbn' => '9788126527558',
                'description' => 'Principles of automatic control systems',
                'publisher' => 'Wiley',
                'publication_year' => 2011,
                'quantity' => 8,
                'available_quantity' => 8,
                'shelf_location' => 'B5-S2',
                'category' => 'Electronics',
                //  'semester' => 6,
                'course_id' => 4,
                'is_available' => true,
            ],
            [
                'title' => 'Heat and Mass Transfer',
                'author' => 'R. K. Rajput',
                'isbn' => '9788131808002',
                'description' => 'Transfer mechanisms in thermal systems',
                'publisher' => 'S. Chand',
                'publication_year' => 2014,
                'quantity' => 6,
                'available_quantity' => 6,
                'shelf_location' => 'C6-S2',
                'category' => 'Mechanical Engineering',
                //  'semester' => 6,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Principles of Economics',
                'author' => 'N. Gregory Mankiw',
                'isbn' => '9788131533332',
                'description' => 'Core principles of micro and macroeconomics',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2020,
                'quantity' => 14,
                'available_quantity' => 14,
                'shelf_location' => 'D5-S2',
                'category' => 'Business',
                //  'semester' => 1,
                'course_id' => 6,
                'is_available' => true,
            ],
            [
                'title' => 'Machine Learning',
                'author' => 'Tom M. Mitchell',
                'isbn' => '9780070428072',
                'description' => 'Foundational concepts in machine learning',
                'publisher' => 'McGraw-Hill',
                'publication_year' => 1997,
                'quantity' => 13,
                'available_quantity' => 13,
                'shelf_location' => 'A4-S1',
                'category' => 'Computer Science',
                //  'semester' => 6,
                'course_id' => 1,
                'is_available' => true,
            ],
            [
                'title' => 'Signals and Systems',
                'author' => 'Alan V. Oppenheim',
                'isbn' => '9780138147570',
                'description' => 'Concepts of signal processing and system analysis',
                'publisher' => 'Prentice Hall',
                'publication_year' => 1996,
                'quantity' => 11,
                'available_quantity' => 11,
                'shelf_location' => 'B4-S2',
                'category' => 'Electronics',
                //  'semester' => 4,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Fluid Mechanics',
                'author' => 'Frank M. White',
                'isbn' => '9780073398273',
                'description' => 'Theory and applications of fluid mechanics',
                'publisher' => 'McGraw-Hill Education',
                'publication_year' => 2015,
                'quantity' => 9,
                'available_quantity' => 9,
                'shelf_location' => 'C4-S3',
                'category' => 'Mechanical Engineering',
                //  'semester' => 5,
                'course_id' => 3,
                'is_available' => true,
            ],
            [
                'title' => 'Engineering Mathematics',
                'author' => 'Erwin Kreyszig',
                'isbn' => '9780470458365',
                'description' => 'Mathematical methods for engineering students',
                'publisher' => 'Wiley',
                'publication_year' => 2011,
                'quantity' => 17,
                'available_quantity' => 17,
                'shelf_location' => 'E1-S1',
                'category' => 'Mathematics',
                //  'semester' => 1,
                'course_id' => 10,
                'is_available' => true,
            ],
            [
                'title' => 'Software Engineering',
                'author' => 'Ian Sommerville',
                'isbn' => '9780137035151',
                'description' => 'Principles of software engineering practices',
                'publisher' => 'Addison-Wesley',
                'publication_year' => 2015,
                'quantity' => 16,
                'available_quantity' => 16,
                'shelf_location' => 'A5-S1',
                'category' => 'Computer Science',
                //  'semester' => 5,
                'course_id' => 13,
                'is_available' => true,
            ],
            [
                'title' => 'Database System Concepts',
                'author' => 'Abraham Silberschatz',
                'isbn' => '9780078022159',
                'description' => 'Concepts and design of database systems',
                'publisher' => 'McGraw-Hill',
                'publication_year' => 2019,
                'quantity' => 14,
                'available_quantity' => 14,
                'shelf_location' => 'A3-S3',
                'category' => 'Computer Science',
                //  'semester' => 4,
                'course_id' => 13,
                'is_available' => true,
            ],
            [
                'title' => 'Control Systems Engineering',
                'author' => 'Norman S. Nise',
                'isbn' => '9788126521165',
                'description' => 'Comprehensive text on control systems',
                'publisher' => 'Wiley India',
                'publication_year' => 2011,
                'quantity' => 12,
                'available_quantity' => 12,
                'shelf_location' => 'B5-S2',
                'category' => 'Electronics',
                //  'semester' => 5,
                'course_id' => 4,
                'is_available' => true,
            ],
            [
                'title' => 'Financial Management',
                'author' => 'Eugene F. Brigham',
                'isbn' => '9781305632295',
                'description' => 'Concepts in corporate finance and financial decision making',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2016,
                'quantity' => 7,
                'available_quantity' => 7,
                'shelf_location' => 'D2-S1',
                'category' => 'Business',
                //  'semester' => 2,
                'course_id' => 9,
                'is_available' => true,
            ],
            [
                'title' => 'Artificial Intelligence: A Modern Approach',
                'author' => 'Stuart Russell',
                'isbn' => '9780136042594',
                'description' => 'Core principles of AI and intelligent agents',
                'publisher' => 'Pearson',
                'publication_year' => 2020,
                'quantity' => 12,
                'available_quantity' => 12,
                'shelf_location' => 'A6-S2',
                'category' => 'Computer Science',
                //  'semester' => 6,
                'course_id' => 13,
                'is_available' => true,
            ],
            [
                'title' => 'VLSI Design',
                'author' => 'Douglas A. Pucknell',
                'isbn' => '9788120320580',
                'description' => 'Introduction to VLSI circuit design',
                'publisher' => 'PHI Learning',
                'publication_year' => 2003,
                'quantity' => 11,
                'available_quantity' => 11,
                'shelf_location' => 'B6-S3',
                'category' => 'Electronics',
                //  'semester' => 6,
                'course_id' => 4,
                'is_available' => true,
            ],
            [
                'title' => 'Linear Algebra and Its Applications',
                'author' => 'Gilbert Strang',
                'isbn' => '9780030105678',
                'description' => 'Introduction to linear algebra concepts',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2006,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'E4-S3',
                'category' => 'Mathematics',
                //  'semester' => 2,
                'course_id' => 12,
                'is_available' => true,
            ],
            [
                'title' => 'Strategic Management',
                'author' => 'Fred R. David',
                'isbn' => '9780133795791',
                'description' => 'A comprehensive guide on strategic management techniques',
                'publisher' => 'Pearson Education',
                'publication_year' => 2017,
                'quantity' => 7,
                'available_quantity' => 7,
                'shelf_location' => 'A4-S2',
                'category' => 'Management',
                //  'semester' => 1,
                'course_id' => 7, // MBA
                'is_available' => true,
            ],
            [
                'title' => 'Microeconomics',
                'author' => 'H.L. Ahuja',
                'isbn' => '9788180388307',
                'description' => 'Study of microeconomic concepts and their applications',
                'publisher' => 'Sultan Chand & Sons',
                'publication_year' => 2019,
                'quantity' => 15,
                'available_quantity' => 15,
                'shelf_location' => 'C7-S3',
                'category' => 'Economics',
                //  'semester' => 5,
                'course_id' => 10, // BSc
                'is_available' => true,
            ],
            [
                'title' => 'Environmental Chemistry',
                'author' => 'A.K. De',
                'isbn' => '9788121902089',
                'description' => 'An introduction to the chemistry of the environment',
                'publisher' => 'Wiley India',
                'publication_year' => 2016,
                'quantity' => 10,
                'available_quantity' => 10,
                'shelf_location' => 'F6-S1',
                'category' => 'Chemistry',
                //  'semester' => 2,
                'course_id' => 11, // MSc
                'is_available' => true,
            ],
            [
                'title' => 'Hotel Operations Management',
                'author' => 'Peter Jones',
                'isbn' => '9781138792149',
                'description' => 'Comprehensive guide to managing hotel operations',
                'publisher' => 'Routledge',
                'publication_year' => 2017,
                'quantity' => 5,
                'available_quantity' => 5,
                'shelf_location' => 'G3-S4',
                'category' => 'Hotel Management',
                //  'semester' => 4,
                'course_id' => 14, // BHM
                'is_available' => true,
            ],
            [
                'title' => 'Introduction to Sociology',
                'author' => 'Anthony Giddens',
                'isbn' => '9781509504349',
                'description' => 'A basic introduction to the study of society and social behavior',
                'publisher' => 'Polity Press',
                'publication_year' => 2014,
                'quantity' => 20,
                'available_quantity' => 20,
                'shelf_location' => 'H2-S3',
                'category' => 'Sociology',
                //  'semester' => 1,
                'course_id' => 15, // BA
                'is_available' => true,
            ]
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
